import { NextPage } from "next";
import Head from "next/head";

const PrivacyPolicyIndexPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
      </Head>

      <h1>Privacy Policy</h1>
      <p>Last updated: October 10, 2024</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and informs You about Your privacy rights under the GDPR and
        CPRA, and how the law protects You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the
        <a
          href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/"
          target="_blank"
        >
          Free Privacy Policy Generator
        </a>
        .
      </p>

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words with capitalized initial letters have meanings defined under
        the following conditions. The following definitions shall have the same
        meaning regardless of whether they appear in singular or plural.
      </p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by, or is under common control with a party, where
          "control" means ownership of 50% or more of the shares, equity
          interest, or other securities entitled to vote for election of
          directors or other managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as "the Company", "We", "Us", or
          "Our" in this Agreement) refers to https://sundarshahithakuri.com.np/.
        </li>
        <li>
          <strong>Cookies</strong> are small files placed on Your computer,
          mobile device, or any other device by a website, containing details of
          Your browsing history on that website among its many uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Nepal.
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, cellphone, or digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual. Under GDPR, Personal Data
          includes, but is not limited to: identifiers like names, email
          addresses, IP addresses, or cookie identifiers. Under CPRA, it
          includes consumer data categories like geolocation, browsing history,
          and employment information.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service, or to assist the
          Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>

      <h4>Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information under GDPR and CPRA
        may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>Usage Data</li>
        <li>Geolocation Data</li>
        <li>Browser and device information</li>
        <li>Browsing and search history</li>
      </ul>

      <h4>Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g., IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers, and other
        diagnostic data.
      </p>

      <h4>Tracking Technologies and Cookies</h4>
      <p>
        We use Cookies and similar tracking technologies to track activity on
        Our Service and store certain information. Technologies We use may
        include:
      </p>
      <ul>
        <li>
          <strong>Browser Cookies:</strong> A cookie is a small file placed on
          Your Device. You can instruct Your browser to refuse all Cookies or to
          indicate when a Cookie is being sent. However, if You do not accept
          Cookies, You may not be able to use some parts of our Service.
        </li>
        <li>
          <strong>Web Beacons:</strong> Small electronic files that permit the
          Company to count users who have visited certain pages or opened an
          email.
        </li>
      </ul>

      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>
          To provide and maintain our Service, including monitoring usage.
        </li>
        <li>
          To manage Your account and registration as a user of the Service.
        </li>
        <li>To perform a contract, such as processing purchases.</li>
        <li>To contact You regarding updates, offers, or similar services.</li>
        <li>
          To comply with legal obligations (GDPR/CPRA) and respond to Your data
          rights requests, such as access, rectification, or deletion.
        </li>
      </ul>

      <h3>GDPR/CPRA Rights</h3>
      <p>
        Under GDPR (for EU residents) and CPRA (for California residents), You
        have the right to:
      </p>
      <ul>
        <li>Access Your personal information.</li>
        <li>Correct inaccurate information.</li>
        <li>Request deletion of Your data.</li>
        <li>Restrict or object to the processing of Your data.</li>
        <li>Portability of Your data (GDPR).</li>
        <li>Opt-out of the sale of Your data (CPRA).</li>
      </ul>

      <h3>Security of Your Personal Data</h3>
      <p>
        We take reasonable measures to protect Your Personal Data. However, no
        method of transmission over the Internet or method of electronic storage
        is 100% secure. We strive to protect Your data but cannot guarantee its
        absolute security.
      </p>

      <h2>Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. You are advised to
        review this page periodically for any changes.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul>
        <li>By email: hello@sundarshahithakuri.com.np</li>
      </ul>
    </>
  );
};

export default PrivacyPolicyIndexPage;
